language: elixir
elixir: 1.6.6
otp_release: 21.3
matrix:
  include:
    - elixir: 1.8.2
      otp_release: 21.3
sudo: false
before_script:
  - epmd -daemon
  - mix deps.get --only test
script:
  - mix test
